---
- name: Lire un secret depuis Vault via AAP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Récupérer le mot de passe depuis Vault
      ansible.builtin.debug:
        msg: >-
          Mot de passe : {{
            lookup('community.hashi_vault.hashi_vault',
              'secret=secret/aap/data/aap:password')
          }}
