---
- name: Test
  hosts: localhost
  collections:
    - community.hashi_vault
  tasks:
    - name: test
      community.hashi_vault.vault_read:
        url: https://rh-salandre-demo-public-vault-9ae71d4d.ead70d08.z1.hashicorp.cloud:8200
        token: hvs.CAESIAj5jvSS0xmYyNwOUnyJfj9D5WMW-Whyc8fwEPy-81OFGikKImh2cy55a0xJMnRhblNJNTVGY3pmNnlteFJxWFEuNW8yekkQxu6GCg
        # engine_mount_point: kv
        # namespace: admin
        path: /v1/aap/data/aap
      register: response

    - name: Display the results
      ansible.builtin.debug:
        msg:
          - "Secret: {{ response.secret }}"
          - "Data: {{ response.data }} (same as secret in kv1)"
          - "Metadata: {{ response.metadata }} (response info in kv1)"
          - "Full response: {{ response.raw }}"
          - "Value of key 'password' in the secret: {{ response.secret.password }}"
