---
- name: Test
  hosts: localhost
  tasks:
    - name: test
      community.hashi_vault.vault_kv1_get:
        url: https://rh-salandre-demo-public-vault-9ae71d4d.ead70d08.z1.hashicorp.cloud:8200
        token: hvs.CAESII0TQTvEs8iq-ZYiM9GfY28cD7vxsJ-Rhu-bOuhWmPOgGikKImh2cy5RMU5tYXNVOUZXcnlwaFozTWNNTDFHekUuNW8yekkQyKD5CQ
        engine_mount_point: kv
        path: /v1/admin/aap/data/aap
      register: vault_data

- name: Display the secret
  ansible.builtin.debug:
    var: vault_data.secret
