---
- name: ReadSecret
  hosts: localhost
  collections:
    - community.hashi_vault
  tasks:
    - name: read
      community.hashi_vault.vault_kv2_get:
        url: https://rh-salandre-demo-public-vault-9ae71d4d.ead70d08.z1.hashicorp.cloud:8200
        engine_mount_point: /admin/aap
        path: aap
        token: hvs.CAESICGYFTVhGLP1f_IgAYIClApJAWs7etd7LvZUGrWRbWmsGikKImh2cy51dG9NTG5WSWtyTHR1bGpBMUpaMWJUenMuNW8yekkQ7tGfCg

        # path equivalent to /v1/admin/aap/data/aap
      register: response

    - name: Display the results
      ansible.builtin.debug:
        msg:
          - "Password: {{ response.secret.password }})"
