---
- name: Vault that requires authentication via username and password
  hosts: localhost
  gather_facts: false
  collections:
    - community.hashi_vault
    
  tasks:
    - name: Read
        community.hashi_vault.vault_kv2_get:
          url: https://rh-salandre-demo-public-vault-9ae71d4d.ead70d08.z1.hashicorp.cloud:8200/
          path: aap
          auth_method: userpass
          username: david2
          password: f6Gxb63AR!LcFD
        register: response
  # equivalent API path is secret/data/hello
  
    - name: Display
        ansible.builtin.debug:
          msg:
            - "Secret: {{ response.secret }}"
            - "Data: {{ response.data }} (contains secret data & metadata in kv2)"
            - "Metadata: {{ response.metadata }}"
            - "Full response: {{ response.raw }}"
            - "Value of key 'password' in the secret: {{ response.secret.password }}"
