---
- name: Vault that requires authentication via username and password
  hosts: localhost
  gather_facts: false
  vars:
    vault_addr: "https://rh-salandre-demo-public-vault-9ae71d4d.ead70d08.z1.hashicorp.cloud:8200"
    vault_user: david2
    vault_password: "f6Gxb63AR!LcFD"
    secret_path: "aap/data/aap"
  
  tasks:
    - name : get the secret
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret={{ secret_path }} field=password auth_method=userpass username={{vault_user}} password={{vault_password}}  url={{ vault_addr }}') }}"
